const fs = require('fs');
const path = require('path');

// Read the CSV file
const csvPath = path.join(__dirname, '../assets/documents.csv');
const outputPath = path.join(__dirname, '../src/data/documents.ts');

try {
  const csvContent = fs.readFileSync(csvPath, 'utf8');
  
  // Generate TypeScript file content
  const tsContent = `// This file is auto-generated from assets/documents.csv
// Do not edit this file directly, edit the CSV file instead

export interface DocumentData {
  id: string;
  title: string;
  category: string;
  type: string;
  year?: string;
  description: string;
  url?: string;
  iconType: 'external' | 'download';
  color: string;
}

// CSV Data
export const csvData = \`${csvContent.trim()}\`;

function parseCSV(csvText: string): DocumentData[] {
  const lines = csvText.trim().split('\\n');
  const headers = lines[0].split(',');
  
  return lines.slice(1).map(line => {
    // Handle CSV with potential commas in quoted fields
    const values: string[] = [];
    let currentValue = '';
    let insideQuotes = false;
    
    for (let i = 0; i < line.length; i++) {
      const char = line[i];
      
      if (char === '"') {
        insideQuotes = !insideQuotes;
      } else if (char === ',' && !insideQuotes) {
        values.push(currentValue.trim());
        currentValue = '';
      } else {
        currentValue += char;
      }
    }
    values.push(currentValue.trim()); // Add the last value
    
    const document: any = {};
    
    headers.forEach((header, index) => {
      const value = values[index]?.trim() || '';
      
      if (header === 'year' && !value) {
        // Skip empty year values
        return;
      }
      if (header === 'iconType') {
        document[header] = value as 'external' | 'download';
      } else {
        document[header] = value;
      }
    });
    
    return document as DocumentData;
  });
}

export function loadDocuments(): DocumentData[] {
  return parseCSV(csvData);
}
`;

  // Ensure the output directory exists
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write the TypeScript file
  fs.writeFileSync(outputPath, tsContent, 'utf8');
  
  console.log('✅ Documents data generated successfully!');
  console.log(`📄 Input: ${csvPath}`);
  console.log(`📄 Output: ${outputPath}`);
  
} catch (error) {
  console.error('❌ Error generating documents data:', error);
  process.exit(1);
}
